<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to Cart</name>
   <tag></tag>
   <elementGuidId>7139413f-e522-42ab-9a64-234003d26630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='submit.add-to-cart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>852675ff-3079-4016-af1a-f43105d28efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit.add-to-cart</value>
      <webElementGuid>470fdde8-efa6-421a-95aa-ba1eca97a8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-spacing-small a-button-primary a-button-icon natc-enabled</value>
      <webElementGuid>688ad626-e1c2-417f-8ded-bc1b9ba39ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>5ddcf264-22ed-482e-bf14-43c6b935ea2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit.add-to-cart&quot;)</value>
      <webElementGuid>b538fc6b-086c-40de-9e04-95789efaca10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='submit.add-to-cart']</value>
      <webElementGuid>8f7d0499-c592-408b-b1b1-8c0315737fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='atc-declarative']/span</value>
      <webElementGuid>60eba0ac-4d16-4988-ac2b-17b5c60461f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/span/span</value>
      <webElementGuid>93c3e024-952d-4a7b-848b-c78d374392c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'submit.add-to-cart' and (text() = 'Add to Cart' or . = 'Add to Cart')]</value>
      <webElementGuid>b076fe43-6a21-4852-acec-9809602e80ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
