<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Amazon_ValidateSearchFieldItem_TListener</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>06e85e51-944f-42a9-bfa0-5eb0b1ab0410</testSuiteGuid>
   <testCaseLink>
      <guid>4ae44cbd-5530-4a93-b56c-8a852bb03c3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Amazon_Search_Item_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9dfe5072-e8bb-4167-9c59-c93f5ec46edb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_TestData/Amazon_SearchField_Item_TestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9dfe5072-e8bb-4167-9c59-c93f5ec46edb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>f2a575d6-0ffa-4c99-8ae6-53a4cdde2844</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9dfe5072-e8bb-4167-9c59-c93f5ec46edb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>f630a078-dfa2-4e76-9028-5f42f73f2161</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
