<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Best Seller_s-image</name>
   <tag></tag>
   <elementGuidId>eeb904b9-1c5c-476b-ace5-d384dbea2d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/div/div/span/div/div/div[2]/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>edb31a5d-34f4-47b1-9f41-dc8a5a397c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>505be792-3964-4bde-9033-f01a9d43f34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL320_.jpg</value>
      <webElementGuid>0359baba-6593-415d-90ef-59d9a12290f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL320_.jpg 1x, https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL480_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL640_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL800_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL960_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>ab824acb-268b-4ece-96db-0f7aefb6163c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sponsored Ad - Amazon Basics 3 Speed Small Room Air Circulator Fan, 7-Inch Blade, Black, 6.3&quot;D x 11.1&quot;W x 10.9&quot;H</value>
      <webElementGuid>1361c519-0cad-4c8e-b331-178d21d09a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c1bb61ec-0356-4a4c-8242-393bcee569e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>146d4fa7-74fe-411e-b58a-064822366836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c9de5baf-c4b3-4c35-9b69-cdf26e468f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-4-of-24 sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 AdHolder sg-col s-widget-spacing-small sg-col-4-of-20&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot;]/div[@class=&quot;rush-component s-expand-height&quot;]/div[@class=&quot;rush-component s-featured-result-item s-expand-height&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-expand-height puis-include-content-margin puis puis-v2rh3j15wdcp4q29xeaptoa72x6 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section a-spacing-base&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-spacing-small s-height-equalized puis puis-v2rh3j15wdcp4q29xeaptoa72x6&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-square-aspect&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>9812bfd8-e2dd-48fa-8b71-cfc47cdbe663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/div/div/span/div/div/div[2]/span/a/div/img</value>
      <webElementGuid>121fcba0-85a9-4108-8f60-667bde7bd59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sponsored Ad - Amazon Basics 3 Speed Small Room Air Circulator Fan, 7-Inch Blade, Black, 6.3&quot;D x 11.1&quot;W x 10.9&quot;H']</value>
      <webElementGuid>4a8e9310-4e09-44e3-a3ef-94e60f65f0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>d743ed48-e34c-4920-8753-53c5867f7d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/81U06MS2NiL._AC_UL320_.jpg' and @alt = 'Sponsored Ad - Amazon Basics 3 Speed Small Room Air Circulator Fan, 7-Inch Blade, Black, 6.3&quot;D x 11.1&quot;W x 10.9&quot;H']</value>
      <webElementGuid>13ef5ab0-634d-4f8d-9bd0-493e00094d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
